import { addDays, isoDate } from './domain.js';
const id = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
export function createDemo(today = isoDate()) {
  const members = Array.from({ length: 4 }, (_, i) => ({ id: id(i + 1), name: `Membro ${i + 1}`, role: ['Project management', 'Business analysis', 'Delivery', 'Operations'][i], color: ['#527260', '#8871a5', '#ba8251', '#557eac'][i], avatar: '', active: true, created_at: `${addDays(today, -30)}T09:00:00Z`, updated_at: `${addDays(today, -1)}T09:00:00Z` }));
  const clients = ['Orion Banking', 'Nova Insurance', 'Atlas Retail', 'Vertex Energy', 'Lumina Health'].map((name, i) => ({ id: id(100 + i), name, description: 'Cliente dimostrativo · dati interamente fittizi', color: ['#8871a5', '#557eac', '#b56873', '#ba8251', '#518e8b'][i], archived: false, created_at: `${addDays(today, -30)}T09:00:00Z`, updated_at: `${addDays(today, -1)}T09:00:00Z` }));
  const clusters = ['Digital onboarding', 'Customer journey', 'Data & reporting', 'Portale clienti', 'Processi operativi', 'Quality assurance', 'Team & metodo', 'Knowledge hub'].map((name, i) => ({ id: id(200 + i), name, description: 'Area di lavoro dimostrativa', client_id: i < 6 ? clients[i % 5].id : null, color: ['#8871a5', '#557eac', '#b56873', '#ba8251', '#518e8b', '#8871a5', '#527260', '#557eac'][i], archived: false, created_at: `${addDays(today, -28)}T09:00:00Z`, updated_at: `${addDays(today, -1)}T09:00:00Z` }));
  const titles = ['Finalizzare il piano di rilascio', 'Condividere il SAL con il cliente', 'Validare i requisiti di onboarding', 'Preparare la demo del portale', 'Rivedere la matrice dei rischi', 'Consolidare i feedback degli utenti', 'Aggiornare la roadmap di progetto', 'Definire gli obiettivi della settimana', 'Verificare la qualità dei dati', 'Chiudere le anomalie del collaudo', 'Preparare il workshop operativo', 'Allineare le dipendenze tra stream', 'Documentare il nuovo processo', 'Revisionare il piano di test', 'Confermare le milestone del trimestre', 'Aggiornare il registro decisioni', 'Analizzare i tempi di lavorazione', 'Disegnare il flusso di approvazione', 'Organizzare la retrospettiva', 'Validare il report direzionale', 'Raccogliere i requisiti del cliente', 'Pubblicare le linee guida del team', 'Verificare gli accessi al portale', 'Pianificare le attività di migrazione', 'Preparare la sintesi per lo steering', 'Rivedere i criteri di accettazione', 'Completare il passaggio di consegne', 'Ottimizzare il cruscotto operativo', 'Aggiornare la documentazione tecnica', 'Confermare le azioni del meeting', 'Analizzare le richieste di evoluzione', 'Verificare la chiusura delle issue'];
  const tasks = titles.map((title, i) => {
    const cluster = clusters[i % clusters.length];
    const status = ['In corso', 'Da fare', 'Bloccata', 'In corso', 'Da fare', 'Completata', 'Da fare', 'Completata'][i % 8];
    const due = addDays(today, [-2, 0, 2, 0, 4, -5, 7, -1, 10, 3, -3, 1][i % 12]);
    const responsible = [members[i % 4].id];
    if (i % 3 === 0) responsible.push(members[(i + 1) % 4].id);
    if (i % 7 === 0) responsible.push(members[(i + 2) % 4].id);
    const completed_at = status === 'Completata' ? `${addDays(due, i % 2 ? 0 : 1)}T14:00:00Z` : null;
    return { id: id(300 + i), title, description: 'Coordinare le attività con il team, verificare i punti aperti e condividere un risultato chiaro con gli stakeholder.', client_id: cluster.client_id, cluster_id: cluster.id, assignee_ids: responsible, status, priority: ['Alta', 'Media', 'Urgente', 'Alta', 'Media', 'Bassa'][i % 6], due_date: due, created_at: `${addDays(today, -15)}T09:00:00Z`, completed_at, created_by: members[i % 4].id, updated_at: `${addDays(today, -1)}T10:${String(i).padStart(2, '0')}:00Z`, updated_by: members[(i + 1) % 4].id, notes: i % 4 === 0 ? 'Allineamento previsto nel prossimo incontro di team.' : '', checklist: Array.from({ length: 2 + (i % 3 === 0 ? 1 : 0) }, (_, j) => ({ id: id(1000 + i * 3 + j), text: ['Raccogliere materiali e contributi', 'Condividere la versione per revisione', 'Confermare il risultato con il team'][j], completed: status === 'Completata' || (j === 0 && i % 2 === 0), assignee_ids: j === 0 ? responsible : [], due_date: j === 0 ? due : null, position: j, completed_at: status === 'Completata' || (j === 0 && i % 2 === 0) ? `${addDays(today, -1)}T10:00:00Z` : null })) };
  });
  const activity = tasks.slice(0, 8).map((t, i) => ({ id: id(2000 + i), task_id: t.id, task_title: t.title, team_member_id: t.updated_by, event_type: ['task_created', 'status_changed', 'checklist_changed', 'task_updated'][i % 4], details: {}, created_at: `${today}T${String(8 + i).padStart(2, '0')}:00:00Z` }));
  return { members, clients, clusters, tasks, activity };
}
