import { state, currentMember, decorateTasks } from './state.js';
import { config } from './config.js';
import { STATUSES, STATUS_KEYS, PRIORITIES, metrics, filterTasks, sortTasks, overdue, checklistProgress, isoDate } from './domain.js';
import { escape as e, initials, formatDate, safeColor, icon } from './utils.js';
export const NAV = [['dashboard', 'Dashboard', 'grid'], ['my-tasks', 'Le mie attività', 'check'], ['tasks', 'Tutte le attività', 'tasks'], ['board', 'Board', 'board'], ['clients', 'Clienti', 'building'], ['clusters', 'Cluster', 'folder'], ['reports', 'Report', 'chart']];
export const QUICK = [['today', 'Oggi'], ['week', 'Questa settimana'], ['overdue', 'Scadute'], ['all', 'Tutte'], ['urgent', 'Urgenti'], ['progress', 'In corso'], ['blocked', 'Bloccate']];
export const EVENTS = { task_created: 'ha creato un’attività', task_updated: 'ha aggiornato un’attività', status_changed: 'ha cambiato lo stato', priority_changed: 'ha cambiato la priorità', assignee_added: 'ha aggiunto un responsabile', assignee_removed: 'ha rimosso un responsabile', due_date_changed: 'ha aggiornato la scadenza', task_completed: 'ha completato un’attività', checklist_changed: 'ha aggiornato la checklist', task_deleted: 'ha eliminato un’attività' };
export function avatar(member, size = '', title = true) {
  if (!member) return '';
  const photo = /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(member.avatar || '');
  return `<span class="avatar ${size}" style="--avatar-color:${safeColor(member.color)}" ${title ? `title="${e(member.name)}${member.active ? '' : ' · disattivato'}"` : ''}>${photo ? `<img src="${e(member.avatar)}" alt="${e(member.name)}"/>` : e(initials(member.name))}</span>`;
}
export function assignees(ids, max = 3) {
  const people = ids.map(id => state.data.members.find(m => m.id === id)).filter(Boolean);
  return `<span class="avatar-stack" aria-label="${e(people.map(p => p.name).join(', '))}">${people.slice(0, max).map(m => avatar(m, 'small')).join('')}${people.length > max ? `<span class="avatar small overflow">+${people.length - max}</span>` : ''}</span>`;
}
export function statusPill(status) { return `<span class="status ${STATUS_KEYS[STATUSES.indexOf(status)]}"><i></i>${e(status)}</span>`; }
export function priorityPill(priority) { return `<span class="priority p${PRIORITIES.indexOf(priority)}"><span class="priority-bars">${[0, 1, 2].map(i => `<i style="opacity:${i <= Math.min(PRIORITIES.indexOf(priority), 2) ? 1 : .22}"></i>`).join('')}</span>${e(priority)}</span>`; }
export function progress(task) {
  const p = checklistProgress(task);
  return `<span class="check-progress" title="${p.percent}% checklist completata"><span class="mini-track"><span style="width:${p.percent}%"></span></span><span>${p.done}<span class="muted">/${p.total}</span></span></span>`;
}
export function dueLabel(task) {
  const late = overdue(task), today = task.due_date === isoDate();
  return `<span class="due ${late ? 'late' : today && task.status !== 'Completata' ? 'today' : ''}">${late ? icon('alert', 13) : ''}${today ? 'Oggi' : formatDate(task.due_date)}${late ? '<span class="sr-only">, scaduta</span>' : ''}</span>`;
}
export function visibleTasks() {
  const filters = { ...state.filters, search: state.search };
  if (state.view === 'my-tasks' || (state.view === 'dashboard' && state.dashboardScope === 'personal')) filters.member = state.memberId;
  if (['my-tasks', 'dashboard'].includes(state.view)) filters.quick = state.quick;
  return sortTasks(filterTasks(decorateTasks(), filters), state.sort, state.direction);
}
export function empty(message = 'Nessuna attività qui, per ora.', subtitle = 'Un po’ di spazio per concentrarsi su ciò che conta.', action = true) {
  return `<div class="empty"><span class="empty-icon">${icon('check', 28)}</span><h3>${e(message)}</h3><p>${e(subtitle)}</p>${action ? '<button class="btn secondary" data-action="new-task">Crea un’attività</button>' : ''}</div>`;
}
const options = (items, selected, blank) => `<option value="">${blank}</option>${items.map(x => `<option value="${e(x.id || x)}" ${(x.id || x) === selected ? 'selected' : ''}>${e(x.name || x)}${x.archived || x.active === false ? ' · archiviato' : ''}</option>`).join('')}`;
export function quickTabs() {
  const source = (state.view === 'my-tasks' || state.dashboardScope === 'personal') ? state.data.tasks.filter(t => t.assignee_ids.includes(state.memberId)) : state.data.tasks;
  return `<div class="quick-tabs" role="group" aria-label="Filtri rapidi">${QUICK.map(([id, label]) => `<button class="quick-tab ${state.quick === id ? 'active' : ''}" data-quick="${id}" aria-pressed="${state.quick === id}">${label}<span>${filterTasks(source, { quick: id }).length}</span></button>`).join('')}</div>`;
}
export function filterBar() {
  const count = Object.values(state.filters).filter(Boolean).length;
  return `<div class="filter-toolbar"><span class="result-count">${visibleTasks().length} attività${state.search ? ` per “${e(state.search)}”` : ''}</span><div class="toolbar-actions"><button class="btn small ${state.showFilters ? 'active-filter' : 'ghost'}" data-action="toggle-filters" aria-expanded="${state.showFilters}">${icon('filter', 16)}Filtri${count ? ` <span class="count">${count}</span>` : ''}</button>${count || state.search ? '<button class="text-button" data-action="reset-filters">Reset filtri</button>' : ''}</div></div>
  ${state.showFilters ? `<div class="filter-grid">
    <label>Cliente<select data-filter="client">${options(state.data.clients, state.filters.client, 'Tutti i clienti')}</select></label>
    <label>Cluster<select data-filter="cluster">${options(state.data.clusters.filter(c => !state.filters.client || !c.client_id || c.client_id === state.filters.client), state.filters.cluster, 'Tutti i cluster')}</select></label>
    <label>Responsabile<select data-filter="member">${options(state.data.members, state.filters.member, 'Tutto il team')}</select></label>
    <label>Stato<select data-filter="status">${options(STATUSES, state.filters.status, 'Tutti gli stati')}</select></label>
    <label>Priorità<select data-filter="priority">${options(PRIORITIES, state.filters.priority, 'Tutte le priorità')}</select></label>
    <label>Scadenza dal<input type="date" data-filter="from" value="${e(state.filters.from)}"/></label>
    <label>Scadenza al<input type="date" data-filter="to" value="${e(state.filters.to)}"/></label>
    <label class="checkbox-label"><input type="checkbox" data-filter="incomplete" ${state.filters.incomplete ? 'checked' : ''}/>Checklist incomplete</label>
  </div>` : ''}`;
}
export function taskTable(tasks, compact = false) {
  if (!tasks.length) return empty();
  const heads = compact ? [['title', 'Attività'], ['priority', 'Priorità'], ['status', 'Stato'], ['due_date', 'Scadenza']] : [['title', 'Attività'], ['client_name', 'Cliente'], ['cluster_name', 'Cluster'], ['assignee_names', 'Responsabili'], ['priority', 'Priorità'], ['status', 'Stato'], ['checklist', 'Checklist'], ['due_date', 'Scadenza'], ['updated_at', 'Aggiornamento']];
  return `<div class="table-scroll"><table class="task-table ${compact ? 'compact' : ''}"><thead><tr>${heads.map(([key, label]) => `<th aria-sort="${state.sort === key ? state.direction === 'asc' ? 'ascending' : 'descending' : 'none'}"><button data-sort="${key}">${label}${state.sort === key ? icon(state.direction === 'asc' ? 'up' : 'down', 12) : ''}</button></th>`).join('')}<th><span class="sr-only">Azioni</span></th></tr></thead><tbody>${tasks.map(t => `<tr class="${t.status === 'Completata' ? 'completed-row' : ''}">
  <td><div class="task-title-cell"><button class="complete-toggle ${t.status === 'Completata' ? 'checked' : ''}" data-complete="${t.id}" aria-label="${t.status === 'Completata' ? 'Riapri' : 'Completa'} ${e(t.title)}">${t.status === 'Completata' ? icon('check', 12) : ''}</button><button class="task-open" data-open-task="${t.id}"><strong>${e(t.title)}</strong>${compact ? `<span>${e(t.client_name || 'Team ENG')}<span class="separator">/</span>${e(t.cluster_name || 'Generale')}</span>` : ''}</button></div></td>
  ${compact ? '' : `<td><span class="client-label"><i style="background:${safeColor(state.data.clients.find(c => c.id === t.client_id)?.color)}"></i>${e(t.client_name || 'Interno')}</span></td><td><span class="cluster-label">${e(t.cluster_name || '—')}</span></td><td>${assignees(t.assignee_ids)}</td>`}
  <td>${priorityPill(t.priority)}</td><td><select class="status-select ${STATUS_KEYS[STATUSES.indexOf(t.status)]}" data-status-task="${t.id}" aria-label="Stato di ${e(t.title)}">${STATUSES.map(s => `<option ${s === t.status ? 'selected' : ''}>${s}</option>`).join('')}</select></td>
  ${compact ? '' : `<td>${progress(t)}</td>`}<td>${dueLabel(t)}</td>${compact ? '' : `<td><span class="updated-date" title="${e(state.data.members.find(m => m.id === t.updated_by)?.name || '')}">${formatDate(t.updated_at)}</span></td>`}
  <td><button class="icon-button" data-open-task="${t.id}" aria-label="Apri ${e(t.title)}">${icon('chevron', 16)}</button></td></tr>`).join('')}</tbody></table></div>`;
}
export function kpiCards(kpi, personal = false) {
  const cards = [['open', 'Attività aperte', 'tasks', `${kpi.todo} da fare · ${kpi.inProgress} in corso`, ''], ['dueSoon', 'In scadenza', 'calendar', 'Da oggi ai prossimi 7 giorni', ''], ['overdue', 'Attività scadute', 'clock', kpi.overdue ? 'Da riportare al centro' : 'Tutte le scadenze sotto controllo', 'warning'], ['completed', 'Completate', 'check', `${kpi.completionRate}% delle ${personal ? 'tue' : 'tutte le'} attività`, 'success']];
  return `<div class="kpi-grid">${cards.map(([key, label, symbol, hint, style]) => `<article class="kpi-card ${style}"><div class="kpi-label">${label}<span class="kpi-icon">${icon(symbol, 17)}</span></div><div class="kpi-value">${kpi[key]}${key === 'completed' ? `<span class="kpi-percent">${kpi.completionRate}%</span>` : ''}</div><div class="kpi-hint">${e(hint)}</div>${key === 'completed' ? `<div class="kpi-track"><span style="width:${kpi.completionRate}%"></span></div>` : ''}</article>`).join('')}</div>`;
}
export function workload() {
  const people = state.data.members.filter(m => m.active);
  const rows = people.map(m => ({ member: m, k: metrics(state.data.tasks.filter(t => t.assignee_ids.includes(m.id))) }));
  const max = Math.max(1, ...rows.map(r => r.k.open));
  return `<article class="surface workload"><div class="section-heading"><h2>Il team, a colpo d’occhio</h2>${icon('users', 18)}</div><p class="subtle">Carico di attività aperte</p><div class="workload-rows">${rows.map(({ member: m, k }) => `<button class="workload-row" data-member-filter="${m.id}"><span class="workload-person">${avatar(m, 'small')}<span>${e(m.name)}</span><strong>${k.open}</strong></span><span class="workload-track"><span style="width:${k.open / max * 100}%;background:${safeColor(m.color)}"></span></span><span class="workload-meta">${k.inProgress} in corso <span>${k.overdue ? `${k.overdue} scadute` : 'In linea'}</span></span></button>`).join('')}</div><div class="card-footnote">Le attività condivise contano per ogni responsabile.</div></article>`;
}
export function activityList(taskId = null, limit = 5) {
  const list = state.data.activity.filter(a => !taskId || a.task_id === taskId).sort((a, b) => b.created_at.localeCompare(a.created_at)).slice(0, limit);
  return list.length ? `<div class="activity-list">${list.map(a => `<div class="activity-row">${avatar(state.data.members.find(m => m.id === a.team_member_id), 'small')}<div><p><strong>${e(state.data.members.find(m => m.id === a.team_member_id)?.name || 'Membro disattivato')}</strong> ${EVENTS[a.event_type] || e(a.event_type)}</p>${!taskId ? `<button class="activity-task" ${a.task_id ? `data-open-task="${a.task_id}"` : 'disabled'}>${e(a.task_title)}</button>` : ''}${a.details?.to ? `<span class="log-detail">${e(a.details.from || 'Nessuna')} → ${e(a.details.to)}</span>` : ''}<time>${formatDate(a.created_at, { hour: '2-digit', minute: '2-digit' })}</time></div></div>`).join('')}</div>` : '<p class="subtle">Lo storico di questa attività apparirà qui.</p>';
}
function dashboard() {
  const personal = state.dashboardScope === 'personal';
  const tasks = personal ? state.data.tasks.filter(t => t.assignee_ids.includes(state.memberId)) : state.data.tasks;
  const k = metrics(tasks);
  return `<div class="hero"><div><div class="eyebrow">IL TUO SPAZIO OPERATIVO</div><h1>${personal ? `Ciao, ${e(currentMember()?.name)}<span class="greeting-dot">.</span>` : 'Insieme, tutto sotto controllo.'}</h1><p>${k.overdue ? `Ci sono ${k.overdue} attività scadute da rimettere in movimento.` : 'Una visione chiara. Un passo avanti, ogni giorno.'}</p></div><div class="segmented" aria-label="Ambito dashboard"><button data-scope="personal" class="${personal ? 'active' : ''}">Personale</button><button data-scope="team" class="${!personal ? 'active' : ''}">Team</button></div></div>
  ${kpiCards(k, personal)}<div class="dashboard-grid"><section class="surface focus-tasks"><div class="section-heading"><div><div class="eyebrow">FOCUS</div><h2>${personal ? 'Le mie attività' : 'Le attività del team'}</h2></div><button class="text-button" data-nav="${personal ? 'my-tasks' : 'tasks'}">Vedi tutte ${icon('arrow', 15)}</button></div>${quickTabs()}${filterBar()}${taskTable(visibleTasks().slice(0, 8), true)}${visibleTasks().length > 8 ? `<button class="load-more" data-nav="${personal ? 'my-tasks' : 'tasks'}">Vedi tutte le ${visibleTasks().length} attività ${icon('arrow', 15)}</button>` : ''}</section>${workload()}</div>
  <div class="dashboard-bottom"><section class="surface"><div class="section-heading"><h2>Ultimi movimenti</h2><span class="subtle">Lo spazio si aggiorna con voi</span></div>${activityList()}</section><section class="focus-note"><div class="note-mark">${icon('sun', 25)}</div><div class="eyebrow">MENO RUMORE, PIÙ FOCUS</div><h2>Le priorità chiare.<br/>Il prossimo passo, anche.</h2><p>${k.blocked ? `${k.blocked} attività bloccate aspettano una decisione. Un breve confronto può fare la differenza.` : 'Il lavoro migliore parte da una visione condivisa. Tieni aggiornati stato, scadenza e responsabili.'}</p><button class="text-button" data-show-blocked>Guarda le attività bloccate ${icon('arrow', 16)}</button></section></div>`;
}
function board() {
  const tasks = visibleTasks();
  return `<section class="surface board-filter">${filterBar()}</section><div class="board-grid">${STATUSES.map((status, i) => {
    const list = tasks.filter(t => t.status === status);
    return `<section class="board-column ${STATUS_KEYS[i]}" data-drop-status="${status}" aria-label="${status}"><div class="board-heading">${statusPill(status)}<span class="count">${list.length}</span><button class="icon-button" data-new-status="${status}" aria-label="Nuova attività ${status}">${icon('plus', 16)}</button></div><div class="board-cards">${list.map(t => `<article class="board-card" data-drag-task="${t.id}"><div class="card-context"><span>${e(t.client_name || 'Team ENG')}</span><button class="icon-button" data-open-task="${t.id}" aria-label="Apri ${e(t.title)}">${icon('more', 16)}</button></div><button class="board-title" data-open-task="${t.id}">${e(t.title)}</button><span class="cluster-label">${e(t.cluster_name || 'Generale')}</span><div class="board-card-tags">${priorityPill(t.priority)}${dueLabel(t)}</div><div class="board-card-footer">${assignees(t.assignee_ids)}${progress(t)}</div><label class="sr-only" for="board-status-${t.id}">Sposta ${e(t.title)}</label><select id="board-status-${t.id}" class="board-move" data-status-task="${t.id}">${STATUSES.map(s => `<option ${s === t.status ? 'selected' : ''}>${s}</option>`).join('')}</select></article>`).join('')}<button class="board-add" data-new-status="${status}">${icon('plus', 15)}Aggiungi attività</button></div></section>`;
  }).join('')}</div>`;
}
function entities(kind) {
  const list = state.data[kind].filter(c => state.archived || !c.archived).filter(c => `${c.name} ${c.description}`.toLowerCase().includes(state.search.toLowerCase()));
  return `<div class="entity-toolbar"><span class="subtle">${list.length} ${kind === 'clients' ? 'clienti' : 'cluster'}</span><label class="checkbox-label"><input type="checkbox" id="show-archived" ${state.archived ? 'checked' : ''}/>Mostra archiviati</label><button class="btn primary" data-new-entity="${kind}">${icon('plus', 16)}${kind === 'clients' ? 'Nuovo cliente' : 'Nuovo cluster'}</button></div><div class="entity-grid">${list.map(c => {
    const m = metrics(state.data.tasks.filter(t => t[kind === 'clients' ? 'client_id' : 'cluster_id'] === c.id));
    const clusters = kind === 'clients' ? state.data.clusters.filter(x => x.client_id === c.id) : [];
    return `<article class="surface entity-card"><div class="entity-card-top"><span class="entity-icon" style="--entity-color:${safeColor(c.color)}">${icon(kind === 'clients' ? 'building' : 'folder', 23)}</span><button class="icon-button" data-edit-entity="${c.id}" data-kind="${kind}" aria-label="Modifica ${e(c.name)}">${icon('edit', 17)}</button></div><h2>${e(c.name)}</h2><p class="entity-description">${e(kind === 'clusters' ? state.data.clients.find(x => x.id === c.client_id)?.name || 'Interno · Team ENG' : c.description || 'Nessuna descrizione')}</p>${c.archived ? '<span class="archive-tag">Archiviato</span>' : ''}<div class="entity-numbers"><div><strong>${m.open}</strong><span>Aperte</span></div><div><strong>${m.completed}</strong><span>Completate</span></div><div><strong class="${m.overdue ? 'danger-text' : ''}">${m.overdue}</strong><span>Scadute</span></div></div><div class="entity-progress"><span>Completamento</span><strong>${m.completionRate}%</strong></div><div class="track"><span style="width:${m.completionRate}%;background:${safeColor(c.color)}"></span></div><div class="entity-meta">${m.total} totali · ${m.blocked} bloccate · ${m.urgent} urgenti</div>${kind === 'clients' ? `<div class="cluster-chips">${clusters.map(x => `<button data-cluster-filter="${x.id}" title="Apri attività di ${e(x.name)}">${e(x.name)}${x.archived ? ' · archiviato' : ''}</button>`).join('') || '<span class="subtle">Nessun cluster associato</span>'}</div><span class="subtle">${clusters.filter(x => !x.archived).length} cluster attivi</span>` : ''}<button class="entity-link" data-entity-filter="${c.id}" data-kind="${kind}">Vedi attività ${icon('arrow', 16)}</button></article>`;
  }).join('')}</div>${!list.length ? empty('Nessun elemento trovato.', 'Crea il primo elemento o modifica la ricerca.', false) : ''}`;
}
function metricsTable(rows, label, extra = false) {
  return `<div class="table-scroll"><table class="report-table"><thead><tr><th>${label}</th><th>Totali</th><th>Aperte</th><th>In corso</th><th>Bloccate</th><th>Urgenti</th><th>Scadute</th><th>Questa settimana</th><th>Completate</th><th>Completamento</th>${extra ? '<th>Cluster attivi</th>' : ''}</tr></thead><tbody>${rows.map(r => `<tr><th>${e(r.name)}</th>${['total','open','inProgress','blocked','urgent','overdue','thisWeek','completed'].map(key => `<td>${r.k[key]}</td>`).join('')}<td>${r.k.completionRate}%</td>${extra ? `<td>${r.clusters}</td>` : ''}</tr>`).join('')}</tbody></table></div>`;
}
function reports() {
  const k = metrics(state.data.tasks);
  const rows = kind => state.data[kind].map(x => ({ name: x.name + (x.archived || x.active === false ? ' (archiviato)' : ''), k: metrics(state.data.tasks.filter(t => kind === 'members' ? t.assignee_ids.includes(x.id) : t[kind === 'clients' ? 'client_id' : 'cluster_id'] === x.id)), clusters: state.data.clusters.filter(c => c.client_id === x.id && !c.archived).length }));
  const percentages = [k.todo, k.inProgress, k.blocked, k.completed].map(n => k.total ? n / k.total * 100 : 0);
  const segments = percentages.reduce((a, n, i) => [...a, (a[i - 1] || 0) + n], []);
  return `${kpiCards(k)}<div class="report-charts"><section class="surface"><div class="section-heading"><h2>Stato del lavoro</h2><span class="subtle">${k.total} attività uniche</span></div><div class="donut-layout"><div class="donut" style="background:${k.total ? `conic-gradient(#a4adb0 0% ${segments[0]}%,#719581 ${segments[0]}% ${segments[1]}%,#d79b78 ${segments[1]}% ${segments[2]}%,#c5eea1 ${segments[2]}% 100%)` : '#eee'}"><div><strong>${k.completionRate}%</strong><span>completamento</span></div></div><div class="chart-legend">${STATUSES.map((s, i) => `<div>${statusPill(s)}<strong>${[k.todo,k.inProgress,k.blocked,k.completed][i]}</strong></div>`).join('')}</div></div></section>${workload()}<section class="surface quality-card"><div class="section-heading"><h2>Qualità della delivery</h2>${icon('chart')}</div>${[['Completate entro scadenza', k.onTimeRate], ['Attività scadute sul totale', k.overdueRate], ['Checklist completate', k.checklistRate]].map(([label, n]) => `<div class="quality-metric"><span>${label}</span><strong>${n === null ? '—' : `${n}%`}</strong><div class="track"><span style="width:${n || 0}%"></span></div></div>`).join('')}<p class="subtle">Puntualità calcolata sulle attività completate con scadenza. Le percentuali checklist sono ponderate per elemento.</p></section></div>${[['members','KPI per persona','Persona'],['clients','KPI per cliente','Cliente'],['clusters','KPI per cluster','Cluster']].map(([kind,title,label]) => `<section class="surface report-section"><div class="section-heading"><h2>${title}</h2></div>${metricsTable(rows(kind),label,kind === 'clients')}</section>`).join('')}<p class="report-method">I KPI globali contano ogni attività una sola volta. Le attività con più responsabili contribuiscono al carico di ciascuno. Scadenze in giorni di calendario; settimana da lunedì a domenica; completamenti in fuso Europe/Rome. Il report e l’Excel includono tutto il workspace, comprese le anagrafiche archiviate.</p>`;
}
export function renderApp() {
  const member = currentMember();
  const myOpen = metrics(state.data.tasks.filter(t => t.assignee_ids.includes(state.memberId))).open;
  document.getElementById('app').innerHTML = `<div class="app-shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#dashboard" data-nav="dashboard"><span class="brand-mark">${icon('check', 22)}</span><span>ENG<span class="brand-product">workspace</span></span></a><div class="workspace-label">TEAM WORKSPACE<span class="live-dot"></span></div><nav aria-label="Navigazione principale">${NAV.map(([id,label,symbol],i) => `${i === 4 ? '<div class="nav-separator"></div>' : ''}<button class="nav-item ${state.view === id ? 'active' : ''}" data-nav="${id}" ${state.view === id ? 'aria-current="page"' : ''}>${icon(symbol, 19)}<span>${label}</span>${id === 'my-tasks' ? `<span class="nav-count">${myOpen}</span>` : ''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="sidebar-note"><span class="tiny-label">UN TEAM. UNA DIREZIONE.</span><p>Il lavoro scorre meglio<br/>quando è chiaro a tutti.</p><div class="sidebar-avatars">${state.data.members.filter(m => m.active).slice(0, 6).map(m => avatar(m, 'small')).join('')}<button class="mini-plus" data-action="manage-team" aria-label="Gestisci team">${icon('plus', 14)}</button></div></div><button class="team-settings" data-action="manage-team">${icon('users', 17)}Gestisci team</button><div class="user-area">${avatar(member)}<div><strong>${e(member?.name)}</strong><button data-action="switch-member">Cambia utente ${icon('down', 11)}</button></div><button class="icon-button" data-action="logout" aria-label="Esci dal workspace">${icon('logout', 17)}</button></div></div></aside>
  <div class="main-shell"><header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-menu" data-action="mobile-menu" aria-label="Apri menu">${icon('menu')}</button><span>Workspace</span>${icon('chevron', 12)}<strong>${NAV.find(n => n[0] === state.view)?.[1]}</strong></div><div class="topbar-right"><label class="global-search">${icon('search', 17)}<input id="global-search" type="search" value="${e(state.search)}" placeholder="Cerca nel workspace…" aria-label="Ricerca globale"/><kbd>/</kbd></label><div class="today-date">${icon('calendar', 16)}${formatDate(isoDate(), { weekday: 'short' })}</div><button class="btn primary" data-action="new-task" id="new-task-button">${icon('plus', 17)}<span>Nuova attività</span></button></div></header>
  ${config.demo ? '<div class="demo-banner"><span class="live-dot"></span>Demo locale · dati fittizi salvati solo in questo browser. Configura Supabase per lavorare insieme.</div>' : ''}${state.offline ? '<div class="error-banner" role="alert">Connessione non disponibile. I dati potrebbero non essere aggiornati. <button data-action="refresh">Riprova</button></div>' : ''}
  <main id="main-content">${state.view !== 'dashboard' ? `<div class="page-heading"><div><div class="eyebrow">ENG WORKSPACE</div><h1>${NAV.find(n => n[0] === state.view)?.[1]}</h1><p>${({ 'my-tasks': 'Le tue priorità, nel giusto ordine.', tasks: 'Il lavoro del team, in un’unica vista.', board: 'Ogni attività trova il suo prossimo passo.', clients: 'Relazioni, progetti e risultati.', clusters: 'Uno spazio per ogni progetto e iniziativa.', reports: 'Dati reali per decisioni più chiare.' })[state.view]}</p></div><button class="btn secondary" data-action="export">${icon('download', 16)}Esporta Excel</button></div>` : ''}
  ${state.view === 'dashboard' ? dashboard() : state.view === 'my-tasks' || state.view === 'tasks' ? `<section class="surface tasks-surface">${state.view === 'my-tasks' ? quickTabs() : ''}${filterBar()}${taskTable(visibleTasks())}</section>` : state.view === 'board' ? board() : state.view === 'clients' || state.view === 'clusters' ? entities(state.view) : reports()}
  <footer class="workspace-footer"><span><i class="sync-dot ${state.offline ? 'offline' : ''}"></i>${config.demo ? 'Salvataggio locale' : 'Supabase'}${state.syncedAt ? ` · aggiornato alle ${new Intl.DateTimeFormat('it-IT', { hour: '2-digit', minute: '2-digit' }).format(state.syncedAt)}` : ''}</span><button class="text-button" data-action="export">${icon('download', 14)}Esporta Excel</button><span>Fatto per lavorare, insieme.</span></footer></main></div></div>`;
}
export function renderLogin(error = '', loading = false) {
  document.getElementById('app').innerHTML = `<div class="auth-screen"><section class="auth-intro"><div class="brand"><span class="brand-mark">${icon('check', 24)}</span><span>ENG<span class="brand-product">workspace</span></span></div><div><div class="eyebrow">MENO COMPLESSITÀ. PIÙ CHIAREZZA.</div><h1>Il tuo team.<br/>Le vostre priorità.<br/><span>Uno spazio comune.</span></h1><p>Clienti, progetti e attività.<br/>Tutto quello che serve per fare il prossimo passo.</p></div><span class="auth-foot">ENG · Team workspace</span></section><section class="auth-form-section"><form id="login-form" class="auth-form"><span class="auth-symbol">${icon('lock', 26)}</span><div class="eyebrow">BENVENUTO NEL WORKSPACE</div><h2>${config.demo ? 'Esplora la demo.' : 'Accedi al tuo spazio.'}</h2><p>${config.demo ? 'Una demo funzionante con dati fittizi. I cambiamenti restano in questo browser e non vengono condivisi con il team.' : 'Usa l’accesso condiviso del team. Poi scegli chi sta lavorando.'}</p>${error ? `<div class="form-error" role="alert">${e(error)}</div>` : ''}${!config.demo ? '<label>Email condivisa<input type="email" name="email" autocomplete="username" placeholder="nome@azienda.it" required/></label><label>Password<input type="password" name="password" autocomplete="current-password" required/></label>' : ''}<button class="btn primary full-width" ${loading ? 'disabled' : ''}>${loading ? 'Accesso in corso…' : config.demo ? 'Apri demo locale' : 'Accedi al workspace'}${icon('arrow', 18)}</button><div class="auth-privacy">${icon('users', 15)}Uno spazio riservato al vostro team.</div></form></section></div>`;
}
export function renderMemberPicker() {
  document.getElementById('app').innerHTML = `<div class="member-screen"><div class="brand dark"><span class="brand-mark">${icon('check', 24)}</span><span>ENG<span class="brand-product">workspace</span></span></div><div class="eyebrow">TUTTO PRONTO</div><h1>Chi sta lavorando?</h1><p>Scegli il tuo nome per trovare subito le tue attività.<br/>Puoi cambiarlo in qualsiasi momento.</p><div class="member-grid">${state.data.members.filter(m => m.active).map(m => `<button class="member-choice" data-select-member="${m.id}">${avatar(m, 'large')}<strong>${e(m.name)}</strong><span>${e(m.role || 'Team ENG')}</span>${icon('arrow', 17)}</button>`).join('')}</div><p class="subtle">${config.demo ? 'Demo locale · nomi provvisori modificabili da “Gestisci team”.' : 'La scelta del nome personalizza il workspace e lo storico delle modifiche.'}</p><button class="text-button" data-action="logout">Esci dal workspace</button></div>`;
}
export function toast(message, error = false) {
  const el = document.createElement('div'); el.className = `toast ${error ? 'error' : ''}`;
  el.innerHTML = `${icon(error ? 'alert' : 'check', 18)}<span>${e(message)}</span><button class="icon-button" aria-label="Chiudi messaggio">${icon('close', 15)}</button>`;
  el.querySelector('button').onclick = () => el.remove();
  document.getElementById('toast-root').append(el);
  setTimeout(() => el.remove(), error ? 14000 : 4500);
}
export { options };
